### ISSUE TITLE
create 2nd sensor from 1st sensor

### ISSUE THREAD

**Issue by xion2000** [lolouk44/CurrentCost_HA_CC#1]
is it possible to use one of the entity id value templates to then create another sensor such as daily total, weekly total, rolling total etc.

**Comment by lolouk44** [comment]
Apologies, I mean to raise an issue on github for the additional data.
For your totals, you can use the [statistics](https://www.home-assistant.io/integrations/statistics/)
Though I think there may be such data inside the currentcost already, I'll investigate
