### ISSUE TITLE
Energy Dashboard Capability

### ISSUE THREAD

**Issue by user897943** [lolouk44/CurrentCost_HA_CC#10]
**Is your feature request related to a problem? Please describe.**
The integration is now perfect for the Energy Dashboard introduced on HA 2021.8.0, unfortunately it is missing something because the entity does not show up.

**Describe the solution you'd like**
Please amend the integration to export the data in a way that can be used by Home Assistant to provide input/consumption data to the Energy Dashboard

**Describe alternatives you've considered**
As this integration already pulls the data from the CC EnviR perfectly well, there is no need to consider buying different hardware, when all this needs is some code adjustments

**Additional context**
Please see: https://www.home-assistant.io/docs/energy/electricity-grid/

**Comment by lolouk44** [comment]
The entity does not show up because the sensor returns real time power consumption in Watts, not energy consumption in KWh.
There may be a way to extract KWh readings from the device (it's technically present under the <hist> meta data), but it's a much bigger task than I have time for right now.
I'll leave this feature request open however as a reminder for when I get some time 😃

**Comment by zbb67** [comment]
Hi,

I guess it would still be best if the KWh figure could be got direct from the CurrentCost device in future, but if any use to others in the meantime - I seem to be getting (decent?) figures in the new HA energy section by using this in configuration.yaml, then the sensor "house_total_energy_total_kw" can be picked from the energy page as a "grid consumption" source.

  # Use Integration to derive kWh from Watts
  - platform: integration
    source: sensor.currentcost_power
    name: house_total_energy_total_kw
    unit_prefix: k
    round: 2

I don't have any way of verifying the accuracy of the derived figure, but it looks reasonable in my case.

Richard

Sources

https://community.home-assistant.io/t/energy-management-in-home-assistant/326854/266

https://www.home-assistant.io/integrations/integration/

**Comment by lolouk44** [comment]
Thanks. your suggestion is by far the easiest (for me).
For me the difficulty in bringing kwh from the CC to HA is trying to figure out how / what to keep from the history bursts.
Here is an example of what the CC returns:
http://www.currentcost.com/cc128/xml.htm and in my case:
[serial_output_history_only.zip](https://github.com/lolouk44/CurrentCost_HA_CC/files/6960883/serial_output_history_only.zip)
I could easily try and extract only the past 2h, and then I'll still need to learn how to tell HA about the time reset for accurate readings....

**Comment by user897943** [comment]
zbb67 solution works perfectly, no need to amend the integration itself, just amend the template that the user needs to include on configuration.yaml to include this one, all sorted, thanks very much! I was pretty much on this line of thinking but didn't have time to investigate and attempt until next weekend, thanks for sharing, glad to find out I was on the right track :)

**Comment by lolouk44** [comment]
I would still like to extract some data from the history, even if for nothing else but to confirm the values calculated by the integration.
I'll see if I can add some attributes like last 2h, last day, last month

**Comment by lolouk44** [comment]
I've now updated the README and INFO pages to also include the additional integration sensor for the Energy Dashboard, so I guess this closes this feature request. Thanks both for your help

**Comment by lolouk44** [comment]
FYI I've added the past 24h and past 30 days energy consumption in KWh to the attributes in [v0.2.0](https://github.com/lolouk44/CurrentCost_HA_CC/releases/tag/0.2.0) 😃

**Comment by zbb67** [comment]
That's great, thank you!
