### ISSUE TITLE
Entity_id is depreciated

### ISSUE THREAD

**Issue by blackest** [lolouk44/CurrentCost_HA_CC#11]
**Is your feature request related to a problem? Please describe.**
The 'entity_id' option near .homeassistant/configuration.yaml:63 is deprecated, please remove it from your configuration
**Describe the solution you'd like**
Probably some form of unique id before homeassistant breaks it.
**Describe alternatives you've considered**

**Additional context**

**Comment by lolouk44** [comment]
Thanks. I am have updated my local copy of the Readme to use the "modern" [template sensor](https://www.home-assistant.io/integrations/template/#state-based-template-sensors) definition and will publish with other changes I'm working on, hopefully including the [long term statistics](https://www.home-assistant.io/blog/2021/08/04/release-20218/#long-term-statistics)
