### ISSUE TITLE
Serial cable

### ISSUE THREAD

**Issue by sgtwilko** [lolouk44/CurrentCost_HA_CC#18]
Hiya,

Sorry not actually a Feature request / Issue.

I have a Current Cost display, but not the serial adapter.
Do you know what the type of cable is, so that I can try to find a compatible cable.

Thanks,

**Comment by lolouk44** [comment]
Any one of these cables should work:
https://shop.technofix.uk/usb-data-cable-for-current-cost-envir-power-monitor-meter
https://www.ebay.co.uk/itm/254180503117
https://www.ebay.co.uk/itm/192872997079
