### ISSUE TITLE
Temperature Data

### ISSUE THREAD

**Issue by yotux** [lolouk44/CurrentCost_HA_CC#9]
While using a Pi3 with Home Assistant 2021.6.3 there is no data for the temperature entry.

**Comment by masxmedia** [comment]
Running Home Assistant core-2021.5.5 on Ubuntu 20.04 x64 I am also having the same issue, no temperature data in the entry, however the wattage works just fine

**Comment by lolouk44** [comment]
Sorry I wasn't notified of new issues for some reason and just picked this up.

Can you confirm which version of the component you're running?
Can you also set the logging level of the component to debug and send the relevant logs from HA?
<details>
  <summary>How to enable Debug Logging?</summary>
To Enable debug logging level, add this to your configuration.yaml and restart:

```
logger:
  default: error
  logs:
    custom_components.currentcost: debug
```
</details>

**Comment by masxmedia** [comment]
Hello !

 

no problem on not being notified. The temp reading isn't important to me, as all I wanted was the power to display and that works fine. 

I'm using 0.1.6, I've added debug to configuration.yaml as described.

 

Thank you! (I must also say, this integration is awesome, I've had my cc128 for many many years, just using the lcd display to read power from. I've long wanted a way to make a virtual gauge and your currentcost component has allowed me to do that.)

 

--Jerre Rose

**Comment by lolouk44** [comment]
> I've added debug to configuration.yaml as described.

Thanks for this. If you can give me the logs so I can have a look at them, then disable the debug else your log file is going to eat your disk space.
Just a thought, where are you located and what temperature format is your CC set up to return?
I wonder if it's a case of Celsius Vs. Farenheit 😉

**Comment by lolouk44** [comment]
Just checking in on this issue as without logs I can't progress it.

**Comment by masxmedia** [comment]
Hello ^^

 

I'm sorry, I got sidetracked and ended up figuring out the issue. It was my own error with template. It now displays temperature.

 

Thank you very much for the support on the issue and for creating an amazing add-on

 

-Jerre

**Comment by lolouk44** [comment]
Thanks @masxmedia 
@yotux can you confirm if you still have this issue or if I can safely close this?

**Comment by lolouk44** [comment]
In case the issue was due to the temp in Fahrenheits, I've made a change in [0.2.1](https://github.com/lolouk44/CurrentCost_HA_CC/releases/tag/0.2.1).
And since there's not been any response I'm now going to close this issue
